(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var s3=function(a){a.ea("cardstatechange",a.Ah()&&a.lk()?1:0)},t3=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},VNa=function(a){var b=g.Sl(a);
a=g.Yl(a);return new g.Cl(b.x,b.y,a.width,a.height)},WNa=function(a){return Math.pow(a,3)},XNa=function(a){return 3*a*a-2*a*a*a},w3=function(a){a=g.Oa(a);
delete u3[a];g.ic(u3)&&v3&&v3.stop()},ZNa=function(){v3||(v3=new g.M(function(){YNa()},20));
var a=v3;a.isActive()||a.start()},YNa=function(){var a=g.Qa();
g.Tb(u3,function(b){$Na(b,a)});
g.ic(u3)||ZNa()},x3=function(a,b,c,d){g.Yq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},$Na=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;aOa(a,a.progress);1==a.progress?(a.i=0,w3(a),a.onFinish(),a.Aw()):a.Ac()&&a.XB()},aOa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},bOa=function(a,b){g.re.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},y3=function(a,b,c,d,e){x3.call(this,b,c,d,e);
this.element=a},z3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
y3.call(this,a,b,c,d,e)},A3=function(a){g.I.call(this);
this.u=a||window;this.i=[]},B3=function(a){return a.baseUrl||null},C3=function(a,b){return g.Do(g.lm(a,b,void 0),function(c){return!!c})},cOa=function(a,b,c){function d(W){var oa,wa,vb,ob=W.hovercardButton;
if(!ob)return null;ob=ob.subscribeButtonRenderer;if(!ob)return null;var $b=f(ob.unsubscribedButtonText),Uc=f(ob.subscribedButtonText);if(ob.subscribed){var bd=f(ob.subscriberCountWithUnsubscribeText);var Se=f(ob.subscriberCountText)}else bd=f(ob.subscriberCountText),Se=f(ob.subscriberCountWithSubscribeText);var ac=null;return W.signinEndpoint&&(ac=t3(W,"signinEndpoint","webNavigationEndpointData","url"),ac||(ac=null===(vb=null===(wa=null===(oa=ob.signInEndpoint)||void 0===oa?void 0:oa.commandMetadata)||
void 0===wa?void 0:wa.webCommandMetadata)||void 0===vb?void 0:vb.url),!ac)?null:$b&&(Uc||ac)?{subscribed:ob.subscribed,subscribeText:$b,subscribeCount:bd,unsubscribeText:Uc,unsubscribeCount:Se,enabled:ob.enabled,signinUrl:ac,classic:W.useClassicSubscribeButton}:null}
function e(W){if(W){var oa=[],wa=W.videoId;wa&&oa.push("v="+wa);(wa=W.playlistId)&&oa.push("list="+wa);(W=W.startTimeSeconds)&&oa.push("t="+W);return"/watch?"+oa.join("&")}}
function f(W){if(!W)return null;var oa=W.simpleText;return oa?oa:W.runs?g.lm(W.runs,function(wa){return wa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,x=!1,y=null,A=null,F=null,G=null,E=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=t3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):A=f(b.subscribersText)}else"WEBSITE"===
h?((F=t3(l,"urlEndpoint","url"))&&(m=F),n=!0,p="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(E=f(b.additionalFeesText)),(n=t3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=t3(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:null,V="";if(b.metadata){var L=f(b.metadata);L&&(V=L)}return{id:"element-"+c,type:h,title:f(b.title),metadata:V,callToAction:f(b.callToAction),KJ:b.image,
iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:A,isSubscribe:x,targetUrl:m||null,yS:n,sessionData:K?{itct:K}:null,jX:p,Fu:a?a:null,BS:b.isPlaceholder,impressionUrls:C3(b.impressionUrls||[],B3),rS:C3(b.hovercardShowUrls||[],B3),clickUrls:C3(l.loggingUrls||[],B3),visualElement:g.Cy(b.trackingParams),
productPrice:G,additionalFeesText:E}},D3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:C3(a.impressionUrls||[],B3),elements:C3(a.elements||[],function(d,e){return cOa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Cy(a.trackingParams));return c},E3=function(a){g.ZM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.Z=!0;this.J=0;a=a.V();this.S=g.dF(a)||g.hF(a);this.events=new g.wD(this);g.J(this,this.events);this.events.T(this.player,g.pA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.qA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.wb);this.events.T(window,"focus",this.nW);this.load();var b=g.zg("STYLE");(g.lg("HEAD")[0]||document.body).appendChild(b);g.qe(this,function(){g.Dg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},dOa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},F3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},eOa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=D3(f,dOa(a))));G3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Up;d&&(c.postParams={ad_tracking:d});if(b=g.epa(b))if(b=g.rf(b),b=g.nf(b))a.B=g.xt(b,c)},G3=function(a,b,c){c=void 0===c?!0:c;
a.player.Ve("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&fOa(a);c=[];d=new g.nA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().i||(a.u=new g.U({G:"div",L:"ytp-ce-shadow"}),g.MM(a.player,a.u.element,4),a.C=new g.zL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=gOa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.MM(a.player,f.element,4);var h=new g.nA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);hOa(a,f,e)}else g.Bz(new g.$v("buildEndscreenElement null",
e))}a.player.Ed(c);a.wb()}},fOa=function(a){var b=g.Gy(),c=g.Iy();
c&&b&&a.endscreen.visualElement&&g.Gz(void 0,c,b,[a.endscreen.visualElement])},gOa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:H3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:I3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-video-title"].concat(g.v(c)),W:{dir:g.hr(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:H3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:I3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-playlist-title"].concat(g.v(c)),W:{dir:g.hr(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={G:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],W:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.hr(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:H3(b)}]};c=new g.U(c);var d=g.mg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.V().i){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.bO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ga:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.hr(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],W:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:H3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:iOa(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.hr(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:H3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.U(a)}b.BS&&g.N(c.element,"ytp-ce-placeholder");return c},H3=function(a){if(a.KJ)var b=a.KJ.thumbnails;
return iOa(b?b[b.length-1].url:null)},iOa=function(a){return a?{style:"background-image: url("+a+")"}:{}},hOa=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.N(b.element,"ytp-ce-force-expand"),J3(a,c.id,!0)):(g.Mq(b.element,"ytp-ce-force-expand"),g.Mq(b.element,"ytp-ce-element-hover"),J3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){K3(a,b,c)});
b.Qa("mouseleave",function(){L3(a,b,c)});
a.player.V().i||b.Qa("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){jOa(a,c,m)});
b.Qa("keypress",function(m){jOa(a,c,m)});
b.Qa("focus",function(){K3(a,b,c)});
b.Qa("blur",function(){L3(a,b,c)});
b.Qa("touchstart",function(){K3(a,b,c)});
var l=g.og("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Mq(b.element,"ytp-ce-element-hover");g.Mq(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.og("ytp-sb-subscribe",b.element));d(g.og("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},jOa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Kq(d,"ytp-ce-element");){g.Kq(d,"subscribe-label")&&M3(a,b);
if(g.Kq(d,"ytp-ce-channel-subscribe"))return;d=g.Eg(d)}if(!d||g.Kq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])L3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.jX)M3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.rf(I3(a,b.targetUrl)),c=g.nf(c),g.BJ(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=I3(a,b.targetUrl),l=b.sessionData,m=g.Hs(h);e&&m&&(m.v||m.list)?a.player.Nj(m.v,l,m.list,!1):
g.AJ(h,l)};
M3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},I3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.GF(a)+b}else return"";return b},K3=function(a,b,c){g.Kq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.V().i?(new g.M(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),N3(a,c.rS),J3(a,c.id,!0))},L3=function(a,b,c){g.Mq(b.element,"ytp-ce-element-hover");
g.Mq(b.element,"ytp-ce-force-expand");J3(a,c.id,!1)},J3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},N3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||F3(a))c&&c();else{b=kOa(a,b);var e=0,f=!1,h=new g.M(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Xu(b[a],d)}},M3=function(a,b,c){N3(a,b.clickUrls,c);
(a=g.Iy())&&b.yS&&g.Mz(a,b.visualElement)},kOa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(lOa(b[d],c));return a},lOa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},mOa=function(a){return"string"===typeof a?a:""},O3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},nOa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},P3=function(a){return a.value?a.value:null},Q3=function(a){if(!a)return null;
var b=g.rf(mOa(a.value));b=g.nf(b);if(!b)return null;var c=O3(a.target,oOa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new nOa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},pOa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},sOa=function(a){if(!a)return null;
var b=O3(a.type,qOa),c=O3(a.trigger,rOa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Q3(a?a:null);return b?new pOa(b,c,a):null},R3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},tOa=function(a,b){return g.rb(a.action,b,void 0)},uOa=function(a,b){this.context=a;
this.i=b},T3=function(a){return a.customMessage?S3("div","iv-card-message",a.customMessage):""},U3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},V3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(S3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},S3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.hr(c);return{G:a,W:b,va:c}},vOa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Yx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Yx+");");c.dir=g.hr(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ga:b,W:c,U:d}},W3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},wOa=function(a,b){this.merchant=a;
this.price=b},xOa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},yOa=function(a,b){return b?b:xOa(a)?"current":"new"},X3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.eb=!1;this.Sa=new Map;this.Ua=new Map;this.context.I.addEventListener(g.pA("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.qA("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)})},Y3=function(a,b,c,d,e,f,h){a.context.i.Qa(b,"click",function(l){a.YB(c,d,e,f||[],h||0,l)});
a.context.i.Qa(b,"touchstart",function(){a.eb=!1});
a.context.i.Qa(b,"touchmove",function(){a.eb=!0})},zOa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Z3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
UN:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
XA:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},b4=function(a,b,c){X3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ja=this.qb=this.B=this.Yd=!1;this.ya=null;this.cards=[];this.kb=this.S=this.Ka=this.D=this.La=this.i=null;this.Y=[];this.K=this.Ae=this.Da=null;this.J=0;this.Aa=new g.M(g.Ha,c.X.rd?4E3:3E3);g.J(this,this.Aa);this.Za=new g.M(g.Ha);g.J(this,this.Za);this.ma=new uOa(c,function(e,f,h,l,m,n){Y3(d,e,f,h,l,m,n)});
this.Z=new g.U({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ga:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.J(this,this.Z);this.C=this.Z.element;this.Ya=new g.zL(this.Z,330);g.J(this,this.Ya);this.jb=g.og("iv-drawer-header-text",this.C);this.u=g.og("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.qb&&$3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.qb=d.B)&&a4(d)})},AOa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){$3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){a4(a)});
var c=b.headerText;g.Gg(a.jb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.Cy(b.trackingParams);a.K=g.Cy(b.closeTrackingParams);a.Ae=g.Cy(b.iconTrackingParams)},BOa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.uA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.command),Dl:d.trackingParams?g.Cy(d.trackingParams):null,Oi:e.trackingParams?
g.Cy(e.trackingParams):null,Ae:f&&f.trackingParams?g.Cy(f.trackingParams):null,imageUrl:d4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.uA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Yx:null,title:d.title?g.uA(d.title):"",customMessage:d.callToAction?g.uA(d.callToAction):"",url:d.command.urlEndpoint.url?Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};e4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.uA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.endpoint),Dl:d.trackingParams?g.Cy(d.trackingParams):null,Oi:e.trackingParams?g.Cy(e.trackingParams):null,Ae:f&&f.trackingParams?
g.Cy(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.uA(d.customText):null,profileImageUrl:d4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.uA(d.channelName):"",metaInfo:[d.subscriberCountText?g.uA(d.subscriberCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
e4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.uA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),Dl:d.trackingParams?g.Cy(d.trackingParams):
null,Oi:e.trackingParams?g.Cy(e.trackingParams):null,Ae:f&&f.trackingParams?g.Cy(f.trackingParams):null,sx:d4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.uA(d.customMessage):null,playlistVideoCount:g.uA(d.playlistVideoCount),title:d.playlistTitle?g.uA(d.playlistTitle):"",metaInfo:[d.channelName?g.uA(d.channelName):"",d.videoCountText?g.uA(d.videoCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:zOa(d.action)})};e4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.uA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),Dl:d.trackingParams?g.Cy(d.trackingParams):null,Oi:e.trackingParams?g.Cy(e.trackingParams):null,Ae:f&&f.trackingParams?g.Cy(f.trackingParams):
null,sx:d4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.uA(d.lengthString):null,customMessage:d.customMessage?g.uA(d.customMessage):null,title:d.videoTitle?g.uA(d.videoTitle):"",metaInfo:[d.channelName?g.uA(d.channelName):"",d.viewCountText?g.uA(d.viewCountText):""],isLiveNow:!!d.badge,url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:zOa(d.action)})};e4(a,b)}a.J++},d4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},c4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},DOa=function(a,b){if(b=COa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.Dg(b.NC),g.zb(a.cards,b),a.by(),f4(a)},$3=function(a,b,c){if(!a.B){a.Ya.show();
a.La=new g.M(function(){g.N(a.context.I.getRootNode(),g.TT.IV_DRAWER_OPEN)},0);
a.La.start();a.ya=g.wu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Iy();d&&a.Da&&a.K&&g.Kz(d,[a.Da,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.yL||(f.yL=!0,EOa(a.context.logger,f.card.tracking.impression,b)),d&&g.Kz(d,[f.card.Dl]);s3(a.I);c&&(a.D=new g.M(function(){a.Ka=a.S;a.kb.focus()},330),a.D.start())}},a4=function(a){a.B&&(a.Ya.hide(),g.xu(a.ya),a.ya=null,g.Mq(a.context.I.getRootNode(),g.TT.IV_DRAWER_OPEN),a.B=!1,s3(a.I),a.D&&a.D.stop(),a.D=new g.M(function(){a.Ka&&(a.Ka.focus(),a.Ka=null)},330),a.D.start())},
GOa=function(a){g.Lq(a.element,[g.TT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.MM(a.I,a.C,5);FOa(a);a.S=g.og("ytp-cards-button",a.I.getRootNode());a.kb=g.og("iv-drawer-close-button",a.C);a.Yd=!0},FOa=function(a){var b=g.og("iv-drawer-close-button",a.C);
a.context.i.Qa(b,"click",a.gR,a);a.context.i.Qa(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Qa(a.u,"scroll",a.sR,a);a.context.u.subscribe("onHideControls",function(){a.Ja=!0});
a.context.u.subscribe("onShowControls",function(){a.Ja=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ja=g.Kq(a.I.getRootNode(),"ytp-autohide")});
a.Y.push(g.dv("iv-button-shown",a.LS,a));a.Y.push(g.dv("iv-button-hidden",a.KS,a));a.Y.push(g.dv("iv-teaser-shown",a.MP,a));a.Y.push(g.dv("iv-teaser-hidden",a.MS,a));a.Y.push(g.dv("iv-teaser-clicked",a.LP,a))},e4=function(a,b){a.Yd||GOa(a);
DOa(a,b.id);var c=HOa(a,b);if(c){var d={card:b,NC:c.element,yL:!1},e=IOa(a,d);g.Gb(a.cards,e,0,d);c.Ea(a.u,e);a.by();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,f4(a),JOa(a,d),$3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&KOa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){KOa(a,d)}),f4(a))}},HOa=function(a,b){switch(b.type){case "simple":a=a.ma;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=vOa(b);c={G:"div",Ga:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?P3(b.url)||"":""},U:[U3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[S3("h2",void 0,b.title),d]}]}]};c=new g.U(c);W3(a,g.ng("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={G:"div",Ga:["iv-card","iv-card-channel"],U:[{G:"a",Ga:["iv-click-target"],W:{href:P3(b.url)||"","data-ytid":b.channelId},U:[U3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[T3(b),{G:"h2",L:"iv-card-primary-link",va:b.title},V3(b)]}]}]},c=new g.U(c),W3(a,g.ng("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={G:"div",Ga:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:P3(b.url)||""},U:[U3(b.sx,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b)]}]}]},c=new g.U(c),
W3(a,g.ng("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.wb(b.offers);c=["iv-card"];d="";var f=vOa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",U:e});e=b.url?P3(b.url)||"":"";c={G:"div",Ga:c,W:{tabindex:"0"},U:[{G:"a",Ga:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[S3("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.zg("span");g.Gg(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.kd(d,"adInfo");W3(a,g.ng("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ga:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null,e={G:"div",Ga:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:P3(c))||""},U:[U3(b.sx,d),{G:"div",L:"iv-card-content",U:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b),f]}]}]},c=new g.U(e),
W3(a,g.ng("iv-click-target",c.element),b,b.url),c;default:return null}},IOa=function(a,b){if(0===a.cards.length)return 0;
a=g.sb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},LOa=function(a){return a.i?"productListing"===a.i.card.type:g.mm(a.cards,function(b){return"productListing"===b.card.type})},f4=function(a){g.O(a.I.getRootNode(),"ytp-cards-shopping-active",LOa(a))},KOa=function(a,b){if(!g.Kq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Iy(),d=a.i?a.i.card.Ae:a.Ae;
c&&d&&g.Lz(c,[d]);a.i=b;f4(a)}if(c="none"!=a.element.style.display)a.context.I.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Ws(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.Ja)&&JOa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
JOa=function(a,b){a.Z.Ab?(b=new x3([0,
a.u.scrollTop],[0,b.NC.offsetTop],600,XNa),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.QK(a.Z,!0),a.u.scrollTop=b.NC.offsetTop,g.QK(a.Z,!1))},g4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},COa=function(a,b){return g.rb(a.cards,function(c){return c.card.id===b})},h4=function(a,b,c){X3.call(this,a,b);
this.annotation=c;this.isActive=!1},MOa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},i4=function(a,b,c){h4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.J=this.D=null},NOa=function(a,b){var c=void 0===c?0:c;
var d=VNa(b).width;g.Ql(b,d);c=new z3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,WNa);g.J(a,c);a.context.B.Qa(c,"begin",function(){g.Zl(b,!0)});
c.play()},QOa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ga:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.bO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Ea(d));var f=a.createElement({G:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Zl(h,!1);var l=a.createElement({G:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.Jl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.M(function(){OOa(a,h,l)},500);
g.J(a,a.B);a.context.i.Qa(a.element,"mouseover",function(){POa(a,h,l,f,b.image_height)});
a.context.i.Qa(a.element,"mouseout",function(){a.B.start()})}},POa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Yl(b);a.i||(b.style.width=g.Pl(f.width,!0),c.style.width=g.Pl(f.width,!0));g.Jl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Jl(d,"right","1px");a.C=!0;g.Zl(b,!0);a.D=new g.M(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},OOa=function(a,b,c){g.Mq(a.element,"iv-branding-active");
a.J=new g.M(function(){g.Zl(b,!1);a.i||(c.style.width=g.Pl(0,!0))},250);
a.J.start();a.C=!1},ROa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.X=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},j4=function(a,b,c){h4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.Z=!1;this.J=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ga:["iv-promo-contents"]});this.D=new g.M(function(){d.i.setAttribute("aria-hidden","true");g.Zl(d.B,!1);g.Zl(d.u,!0)},700,this);
g.J(this,this.D)},SOa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.Wd(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Y3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.Mf(f,P3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
va:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ga:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Y3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.i,
"iv-click-target");e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ga:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.N(a.i,"iv-click-target"),e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Qa(a.u,"click",function(q){k4(a,5E3,q)});
c.appendChild(a.u);g.Zl(a.u,!1);a.context.i.Qa(a.element,"mouseover",a.XR,a);a.context.i.Qa(a.element,"mouseout",a.WR,a);a.context.i.Qa(a.element,"touchend",function(q){k4(a,5E3,q)});
a.B=a.createElement({G:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.SR:a.RR,a);c.appendChild(a.B);g.Lq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},k4=function(a,b,c){c.stopPropagation();
TOa(a);UOa(a,b);a.i.focus()},VOa=function(a){a.isCollapsed||a.S||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},TOa=function(a){a.D.stop();
a.isCollapsed&&(g.Nq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Zl(a.u,!1),g.Zl(a.B,!0))},UOa=function(a,b){a.C||(a.C=g.sh(function(){l4(this);
VOa(this)},b,a))},l4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},WOa=function(a){this.I=a},EOa=function(a,b,c){b&&(c?m4(a,b.map(function(d){return g.xq(d,c)})):m4(a,b))},m4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Xu(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},n4=function(a){g.ZM.call(this,a);
var b=this;this.Z=!1;this.loadNumber=0;this.K={};this.logger=new WOa(this.player);this.D=new g.wD(this);this.J=this.B=null;this.events=new g.wD(this);this.S=this.i=null;this.Y=[];g.J(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ea("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.NP,this);this.subscribe("resize",this.aA,this);this.player.V().Z.subscribe("vast_info_card_add",this.MM,this);g.J(this,this.events);this.ma=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.U({G:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.MM(this.player,this.u.element,4);this.u.hide();this.C=new g.U({G:"div",Ga:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.ma);this.C.element.appendChild(a);this.Bq()&&this.load();var c=this.createElement({G:"style"});(g.lg("HEAD")[0]||document.body).appendChild(c);g.qe(this,function(){g.Dg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},XOa=function(a){a=a.createElement({G:"div",
Ga:["annotation","annotation-type-custom"]});g.Zl(a,!1);return a},YOa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.QK(a.u,b);g.QK(a.C,b)},ZOa=function(a,b,c){a.Z=!0;
a.J=g.xt(b,c)},$Oa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push($Oa(a,e))}return c},cPa=function(a){var b=a.player.getVideoData();
if(b.Sa){var c=a.player.V().Z.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.ot(h)&&h.responseXML?h.responseXML:null)&&o4(a,h)}};
g.Ou()&&(d.onFinish=aPa(a,d.onFinish));d.postParams={ic_only:"1"};bPa(d,c);a.Z=!0;g.xt(b.Sa,d)}}},bPa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Qu&&(a.postParams.ic_coll=b.Qu);b.jy&&(a.postParams.ic_xml=b.jy);b.wx&&(a.postParams.ic_track=b.wx)},dPa=function(a){var b=new g.U({G:"div"});
g.Zl(b.element,!1);var c=new b4(a.player,b.element,p4(a));g.J(c,b);b.Ea(a.u.element);c.bx();return c},p4=function(a){if(!a.S){var b=new A3(a);
g.J(a,b);var c=new g.Yj(a);g.J(a,c);a.S=new ROa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Md)}return a.S},o4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Iy();if(e){var f=g.Gy();f&&g.Gz(void 0,e,f,[g.Cy(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=$Oa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=O3(f.type,ePa),p=O3(f.style,fPa),q=mOa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=sOa;if(null==u)var x=null;else if(g.La(u)){l=[];for(var y=g.r(u),A=y.next();!A.done;A=y.next()){var F=f(A.value);
F&&l.push(F)}x=l}else{var G=f(u);x=G?[G]:[]}e=m&&n?new R3(m,n,p,x,t):null}else e=null}catch(oa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var E=XOa(f),K=null;switch(l.type){case "branding":if(f.player.V().Fb)break;f.u.element.appendChild(E);K=new i4(E,p4(f),l);break;case "promotion":g.MM(f.player,E,4),K=new j4(E,p4(f),l)}K&&K.bx();if(f=K)g.J(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=dPa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var V=e&&e.data&&e.data.card_type;
f=e.data;if(V)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,UN:l.teaser_impression,XA:l.teaser_click},E=f.tracking_params||{},K=null,V){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Dl:E.card?g.Cy(E.card):null,Oi:E.teaser?g.Cy(E.teaser):null,Ae:E.icon?g.Cy(E.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Dl:E.card?g.Cy(E.card):
null,Oi:E.teaser?g.Cy(E.teaser):null,Ae:E.icon?g.Cy(E.icon):null,sx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "productListing":f.signin_url&&(K=Q3({target:"current",value:f.signin_url}));V=[];for(var L=f.offers||[],W=0;W<L.length;W++)V.push(new wOa(g.bg(L[W].merchant),g.bg(L[W].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Dl:E.card?g.Cy(E.card):null,Oi:E.teaser?g.Cy(E.teaser):null,Ae:E.icon?g.Cy(E.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Yx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Saa:K,Raa:f.signin_title?f.signin_title:void 0,Qaa:f.signin_message?f.signin_message:void 0,offers:V};e4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Dl:E.card?g.Cy(E.card):null,Oi:E.teaser?g.Cy(E.teaser):
null,Ae:E.icon?g.Cy(E.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Yx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Dl:E.card?g.Cy(E.card):null,Oi:E.teaser?g.Cy(E.teaser):null,Ae:E.icon?g.Cy(E.icon):null,sx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},e4(c,e)}}else AOa(a.i,e);c=!0}}c&&(s3(a.player),a.aA())},gPa=function(a,b){var c=!1;
a.i||(a.i=dPa(a),g.J(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(BOa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.uA(b.headerText):"",g.Gg(c.jb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.Cy(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Cy(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ae=b.icon.infoCardIconRenderer.trackingParams?
g.Cy(b.icon.infoCardIconRenderer.trackingParams):null,s3(a.player),a.aA())},hPa=function(a,b,c,d,e){if(!a.player.V().Fb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new pOa("openUrl","click",new nOa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.uA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.uA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.uA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.uA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.uA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.uA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new R3(c,"branding","branding",f,d);l=XOa(a);a.u.element.appendChild(l);f=new i4(l,p4(a),f);f.bx();g.J(f,f);a.K[c]=f}},aPa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.Y.push(g.Lu(0,function(){b.apply(null,g.v(d))}))}},iPa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.FM.prototype.Ws=g.ca(17,function(a,b){var c=g.nN(this.ub());c&&c.Ws(a,b)});
var u3={},v3=null;g.Ra(x3,g.Yq);g.k=x3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Ac())return!1;w3(this);this.startTime=a=g.Qa();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.Xz();this.ni("play");-1==this.i&&this.ni("resume");this.i=1;var b=g.Oa(this);b in u3||(u3[b]=this);ZNa();$Na(this,a);return!0};
g.k.stop=function(a){w3(this);this.i=0;a&&(this.progress=1);aOa(this,this.progress);this.ni("stop");this.Aw()};
g.k.pause=function(){this.Ac()&&(w3(this),this.i=-1,this.ni("pause"))};
g.k.xa=function(){0==this.i||this.stop(!1);this.ni("destroy");x3.ke.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.XB=function(){this.ni("animate")};
g.k.ni=function(a){this.dispatchEvent(new bOa(a,this))};
g.Ra(bOa,g.re);g.Ra(y3,x3);y3.prototype.C=g.Ha;y3.prototype.XB=function(){this.C();y3.ke.XB.call(this)};
y3.prototype.Aw=function(){this.C();y3.ke.Aw.call(this)};
y3.prototype.Xz=function(){this.C();y3.ke.Xz.call(this)};
g.Ra(z3,y3);z3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(A3,g.I);A3.prototype.Qa=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.wu(a,b,c);this.i.push(a);return a};
A3.prototype.Dz=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.Fu(a,b,c);this.i.push(a);return a};
A3.prototype.jc=function(a){g.xu(a);g.zb(this.i,a)};
A3.prototype.xa=function(){g.xu(this.i);this.i.length=0;g.I.prototype.xa.call(this)};g.w(E3,g.ZM);g.k=E3.prototype;g.k.load=function(){g.ZM.prototype.load.call(this);if(!F3(this)){var a=g.fpa(this.player.getVideoData());a?(a=D3(a,dOa(this)),G3(this,a,!1)):eOa(this)}};
g.k.unload=function(){G3(this,null);this.B&&(this.B.abort(),this.B=null);g.ZM.prototype.unload.call(this)};
g.k.jf=function(a,b){return F3(this)?"loadCustomEndscreenRenderer"===a?(a=D3(b,"new"),G3(this,a),!0):null:null};
g.k.getOptions=function(){return F3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.wb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<jPa.length;f++){var h=Math.abs(b.width-jPa[f]);if(-1===e||d>=h)e=f,d=h}d=kPa[e];this.u&&g.Jl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Xl(e.element,Math.round(h.width*a.width),f);g.Ql(e.element,m,n);g.Nq(e.element,lPa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Nq(e.element,kPa);g.N(e.element,d);(e=g.mg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Jl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())N3(this,this.endscreen.impressionUrls),(a=g.Iy())&&this.endscreen.visualElement&&g.Hz(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");N3(this,c.impressionUrls);(b=g.Iy())&&g.Hz(b,c.visualElement,void 0);this.player.V().B&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Mq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Mq(b,"ytp-ce-shown");this.player.V().B&&this.player.Oa("endscreenelementhidden",a)}};
g.k.nW=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Nq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var jPa=[346,426,470,506,570,640,853,1280,1920],kPa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),lPa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var oOa={O0:"current",x6:"new"};var qOa={CLOSE:"close",P6:"openUrl",SUBSCRIBE:"subscribe"},rOa={eZ:"click",CLOSE:"close",l2:"hidden",l8:"rollOut",m8:"rollOver",c9:"shown"};R3.prototype.Wd=function(){var a=tOa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var fPa={xY:"anchored",HO:"branding",CHANNEL:"channel",N0:"cta",o2:"highlightText",o3:"label",PLAYLIST:"playlist",H7:"popup",l9:"speech",SUBSCRIBE:"subscribe",D9:"title",VIDEO:"video",L$:"website"},ePa={HO:"branding",RY:"card",e1:"drawer",n2:"highlight",R4:"marker",R7:"promotion",TEXT:"text",R$:"widget"};g.w(X3,g.I);g.k=X3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.nA(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Ua.set(a,e);this.context.I.Ed([a])};
g.k.bx=function(){this.context.u.subscribe("resize",this.by,this)};
g.k.YB=function(a,b,c,d,e,f){if(this.eb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Dg(this.element)};
g.k.by=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=P3(a);if(f){var h=yOa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.Hs(f||"");m&&n&&(n.v||n.list)?e.context.I.Nj(n.v,b,n.list,!1):g.BJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m4(this.context.logger,c,l,d);xOa(f)||(c=g.Iy(),d=b.itct,c&&d&&g.Mz(c,g.Cy(d)))}};
g.k.xa=function(){this.Sa.clear();this.Ua.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.J(this,a);return a.element};g.w(b4,X3);g.k=b4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Yl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.by=function(){var a=this.isAvailable();g.Zl(this.element,a);g.O(this.context.I.getRootNode(),g.TT.IV_DRAWER_ENABLED,a);s3(this.I)};
g.k.destroy=function(){this.I.Ws(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.ev(this.Y);g.xu(this.ya);this.La&&this.La.dispose();this.D&&this.D.dispose();X3.prototype.destroy.call(this)};
g.k.gR=function(){if(this.B){m4(this.context.logger,g4(this).tracking.close);var a=g.Iy();a&&this.K&&g.Mz(a,this.K);a4(this)}};
g.k.sR=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.LS=function(){var a=g.Iy(),b=g4(this);b=b?b.Ae:this.Ae;a&&b&&g.Kz(a,[b])};
g.k.KS=function(){var a=g.Iy(),b=g4(this);b=b?b.Ae:this.Ae;a&&b&&g.Lz(a,[b])};
g.k.MP=function(){var a=g4(this);m4(this.context.logger,a.tracking.UN);var b=g.Iy();b&&a&&g.Kz(b,[a.Oi,a.Ae])};
g.k.MS=function(){var a=g.Iy(),b=g4(this);a&&b&&g.Lz(a,[b.Oi])};
g.k.LP=function(a){var b=g4(this),c=g.Iy();this.i?a?(a=this.context.logger,m4(a,b.tracking.XA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Oi&&g.Mz(c,b.Oi)):(a=this.context.logger,m4(a,b.tracking.XA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Ae&&g.Mz(c,b.Ae)):(a=this.context.logger,m4(a,b.tracking.XA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.Ae&&g.Mz(c,this.Ae))};g.w(h4,X3);h4.prototype.bx=function(){X3.prototype.bx.call(this);MOa(this)};
h4.prototype.show=function(){X3.prototype.show.call(this);var a=g.Iy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Kz(a,[g.Cy(b.itct)])};
h4.prototype.hide=function(){X3.prototype.hide.call(this);var a=g.Iy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Lz(a,[g.Cy(b.itct)])};g.w(i4,h4);
i4.prototype.show=function(){if(!this.isActive){h4.prototype.show.call(this);if(!this.K){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ga:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Zl(this.u,!1);var b=this.createElement({G:"div",Ga:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=this.annotation.Wd())&&Y3(this,this.u,b,this.annotation.id,
a.session_data);QOa(this,a);this.K=!0}g.Zl(this.element,!0);this.isActive=!0;this.u&&NOa(this,this.u)}};
i4.prototype.hide=function(){this.isActive&&(h4.prototype.hide.call(this),g.Zl(this.element,!1),this.isActive=!1)};
i4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);h4.prototype.destroy.call(this)};g.w(j4,h4);g.k=j4.prototype;g.k.show=function(){this.isActive||(h4.prototype.show.call(this),this.Z||(SOa(this),this.Z=!0),g.Zl(this.element,!0),g.sh(function(){g.Mq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,l4(this),TOa(this),UOa(this,this.J))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.YB=function(a,b,c,d,e,f){return this.isCollapsed?!1:h4.prototype.YB.call(this,a,b,c,d,e,f)};
g.k.XR=function(a){this.S=!0;k4(this,500,a)};
g.k.WR=function(){this.S=!1;VOa(this)};
g.k.RR=function(a){a.stopPropagation();this.hide()};
g.k.SR=function(a){a.stopPropagation();l4(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();h4.prototype.destroy.call(this)};g.w(n4,g.ZM);g.k=n4.prototype;g.k.jf=function(a,b){if(!iPa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.T1(b))&&o4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(DOa(this.i,b),s3(this.player)),!0}return null};
g.k.getOptions=function(){return iPa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Bq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.IJ||a.Z.get(b.videoId)||g.RG(b)||g.SG(b)?!0:!1};
g.k.aA=function(){if(this.C){var a=this.player.bb().getVideoContentRect(!0);g.Xl(this.C.element,a.width,a.height);g.Ql(this.C.element,a.left,a.top)}if(this.i){var b=this.player.ij();a=this.i;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.NP=function(a){YOa(this,a.state);g.T(a.state,2)&&(this.Ah()&&this.lk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Ws(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.J=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.ot(h)&&h.responseXML?h.responseXML:null)&&(o4(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.ZM.prototype.load.call(this);YOa(this,this.player.vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Ou()&&(a=aPa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.J=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().Z.get(d);f&&bPa(e,f);f=f&&(f.jy||f.Qu);if(!c.xl||f)c.Sa?ZOa(this,c.Sa,e):(this.B=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.B));
g.MM(this.player,this.C.element,4);this.aA();(f=g.RG(c))&&gPa(this,f);(f=g.SG(c))&&f.featuredChannel&&hPa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Sa&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),ZOa(this,b.Sa,a))};
g.k.unload=function(){this.player.Ve("annotations_module");for(var a=g.r(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.S=null;this.i&&(this.i.destroy(),this.i=null,s3(this.player));this.Z=!1;this.J&&(this.J.abort(),this.J=null);this.K={};this.u.hide();g.ZM.prototype.unload.call(this);this.C.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.k.MM=function(a){a===this.player.getVideoData().videoId&&(this.loaded?cPa(this):this.load())};
g.k.Ah=function(){return!!this.i&&this.i.isAvailable()};
g.k.lk=function(){this.Ah();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ah();this.i&&(a?c?$3(this.i,c,b):$3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):a4(this.i))};
g.k.Ws=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.V().Z.unsubscribe("vast_info_card_add",this.MM,this);g.Mq(this.player.getRootNode(),g.TT.IV_DRAWER_OPEN);for(var a=this.Y,b=0,c=a.length;b<c;b++)g.Pu(a[b]);this.Y.length=0;g.ZM.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.J(this,a);return a.element};g.YM("annotations_module",n4);g.YM("creatorendscreen",E3);})(_yt_player);
